version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3

  kafka:
    image: wurstmeister/kafka
    ports:
        - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "romantic-aggregator:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3

  romantic-aggregator:
    build: .
    image: fberrez/romantic-aggregator
    network_mode: host
    ports:
      - "4242:4242"
    environment:
        GIN_MODE: release
        API_PORT: 4242
        KAFKA_ADDRESS: 127.0.0.1:9092
        KAFKA_TOPIC: romantic-aggregator
    depends_on:
      - "zookeeper"
      - "kafka"
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
